[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "metadata-generator"
dynamic = ["version"]
dependencies = [
  "boto3==1.*",
  "pyarrow==16.*"
]

[tool.setuptools.dynamic]
version = {attr = "metadata_generator.__version__"}
