# Building and testing Python
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on: [ push ]

jobs:
  test:

    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - run: pytest
